apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/auth-api
  - ../../../base/todos-api
  - ../../../base/users-api
  - ../../../base/frontend
  - ../../../base/ingress

namespace: apps

components:
  - ../../../Components/network-policies/app
  - ../../../Components/resource-limits/local

patches:
  - path: patches/replicas-local.yaml