apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/auth-api/deployment.yaml
  - ../../../base/auth-api/service.yaml
  - ../../../base/todos-api/deployment.yaml
  - ../../../base/todos-api/service.yaml
  - ../../../base/users-api/deployment.yaml
  - ../../../base/users-api/service.yaml
  - ../../../base/frontend/deployment.yaml
  - ../../../base/frontend/service.yaml
  - ../../../base/ingress/ingress.yaml

namespace: apps

components:
  - ../../../../components/network-policies
  - ../../../../components/resource-limits/local

patches:
  - path: patches/replicas-local.yaml