# components/resource-limits/local/zipkin.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-server
spec:
  template:
    spec:
      containers:
      - name: zipkin-server
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
            # Zipkin es también Java internamente.
            # Necesita más memoria que los servicios
            # pequeños aunque no tenga Xms explícito.
          limits:
            cpu: "300m"
            memory: "512Mi"