apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:

      - job_name: 'ingress-nginx'
        # Scrapeamos directamente el Service que acabamos
        # de crear en ingress-nginx. Este job recolecta
        # todas las métricas del Ingress Controller
        # incluyendo latencia por servicio, RPS, errores.
        static_configs:
          - targets:
              - ingress-nginx-metrics.ingress-nginx.svc.cluster.local:10254
              # FQDN completo porque Prometheus está en
              # el namespace monitoring, distinto a ingress-nginx.

      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)