apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 
resources:
  - ../../../base/redis/deployment.yaml
  - ../../../base/redis/service.yaml
  - ../../../base/log-processor/deployment.yaml

namespace: messaging