apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 
resources:
  - ../../../base/redis
  - ../../../base/log-processor

namespace: messaging

components:
  - ../../../Components/network-policies/messaging
patches:
  - path: patches/zipkin-url.yaml