apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-api
spec:
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        # Le dice a Prometheus que este pod expone métricas.
        prometheus.io/port: "8082"
        # El puerto donde están las métricas.
        prometheus.io/path: "/metrics"
        # La ruta donde Prometheus debe hacer el scrape.
        # Si tu todos-api no expone /metrics de forma nativa,
        # se vera en el paso de verificación.