apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - app-deny-all.yaml
  - app-allow-rules.yaml
  - messaging-deny-all.yaml
  - messaging-allow-rules.yaml
  - observability-deny-all.yaml
  - observability-allow-rules.yaml
