apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces/
  - auth-api/
  - todos-api/
  - users-api/
  - frontend/
  - ingress/
  - redis/
  - log-processor/
  - zipkin/